# -*- coding: utf-8 -*-
"""mental_health ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1sLftASSGDYp5c30PlRSxUnZdKBkill
"""

import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('Teen_Mental_Health_Dataset.csv')

df.head()

df.info()

df.columns

df.shape

df.isnull().sum()

df.describe()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()

df.hist(figsize=(13,5))
plt.show()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['gender']=le.fit_transform(df['gender'])
df['platform_usage']=le.fit_transform(df['platform_usage'])
df['social_interaction_level']=le.fit_transform(df['social_interaction_level'])

df.info()

X=df.drop('stress_level',axis=1)
y=df['stress_level']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

from sklearn.ensemble import  RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

y_pred

y_test

from sklearn.metrics import accuracy_score ,confusion_matrix,classification_report
score=accuracy_score(y_test,y_pred)

score

cm=confusion_matrix(y_test,y_pred)

cm

import pickle
pickle.dump(model,open('Teen_Mental_Health_Dataset.pkl','wb'))

model=pickle.load(open('Teen_Mental_Health_Dataset.pkl','rb'))

new_prediction = model.predict([X_test.iloc[0]])

print("Prediction:", new_prediction)